name: MLOps Azure animals classification pipeline

on:
  push:
    branches: [ main ]
  workflow_dispatch:

env:
  GROUP: mlops-labo3-tibe
  WORKSPACE: mlops
  LOCATION: westeurope
  CREATE_COMPUTE: true

jobs:
  azure-pipeline:
    runs-on: ubuntu-latest
    # runs-on: self-hosted
    steps:
      - name: 'Checkout out repository'
        uses: actions/checkout@v4

      - name: 'Az CLI login'
        uses: azure/login@v1
        with:
          creds: ${{ secrets.AZURE_CREDENTIALS }}

      - name: 'Run az commands'
        uses: azure/CLI@v1
        id: azure-ml-compute
        if: ${{ env.CREATE_COMPUTE == 'true' }}
        with:
          azcliversion: 2.53.0
          inlineScript: |
            az extension add --name ml -y
            az configure --defaults group=$GROUP workspace=$WORKSPACE location=$LOCATION
            az ml compute create --file ./environment/compute.yaml
      
      - name: 'Start compute'
        uses: azure/CLI@v1
        id: azure-ml-compute-start
        if: ${{ env.CREATE_COMPUTE != 'true' }}
        with:
          azcliversion: 2.53.0
          inlineScript: |
            az extension add --name ml -y
            az configure --defaults group=$GROUP workspace=$WORKSPACE location=$LOCATION
            az ml compute start --name mlopsc-cli
        continue-on-error: true

      - name: 'Run pipeline'
        uses: azure/CLI@v1
        id: azure-ml-pipeline
        if: always()
        with:
          azcliversion: 2.53.0
          inlineScript: |
            az extension add --name ml -y
            az configure --defaults group=$GROUP workspace=$WORKSPACE location=$LOCATION
            az ml job create --file ./pipelines/animals-classification.yaml --set name=animals-classification-${{ github.sha }}-${{ github.run_id }} --stream
            echo "Pipeline Done"
            VERSION=$(az ml model list -n animals-classification --query '[0].version')
            echo "Latest version is $VERSION"
            echo "::set-output name=latest_version::$VERSION"

      - name: 'Cleanup Azure Stop compute'
        uses: azure/CLI@v1
        id: azure-ml-compute-stop
        if: always()
        with:
          azcliversion: 2.53.0
          inlineScript: |
            az extension add --name ml -y
            az configure --defaults group=$GROUP workspace=$WORKSPACE location=$LOCATION
            az ml compute stop -n mlopsc-cli
        continue-on-error: true

      - name: Download model
        uses: azure/CLI@v1
        with:
          azcliversion: 2.53.0
          inlineScript: |
            az extension add --name ml -y
            az configure --defaults group=$GROUP workspace=$WORKSPACE location=$LOCATION
            az ml model download --name animals-classification --download-path ./inference --version "${{ steps.azure-ml-pipeline.outputs.latest_version }}" 

      # - name: Move model
      #   run: |
      #       ls inference/animals-classification/INPUT_model_path
      #       mv inference/animals-classification/INPUT_model_path/animal-cnn inference 

      - name: Gather Docker Meta Information
        id: docker-metadata
        uses: docker/metadata-action@v3
        with:
          # list of Docker images to use as base name for tags
          images: |
            ghcr.io/demeulemeestertibe/mlops-2.0
          # generate Docker tags based on the following events/attributes:
          # The GitHub Branch
          # The GitHub SHA
          # More info: https://github.com/docker/build-push-action/blob/master/docs/advanced/tags-labels.md
          tags: |
            type=ref,event=branch
            type=sha
      
      # Enter your GITHUB Token here!
      - name: Login to GHCR
        uses: docker/login-action@v1
        with:
          registry: ghcr.io
          username: demeulemeestertibe
          password: ${{ secrets.DOCKER_PWD }}

      - name: Docker Build and push
        id: docker_build
        uses: docker/build-push-action@v2
        with:
          context: .
          push: true
          tags: ${{ steps.docker-metadata.outputs.tags }}