name: MLOps Azure animals classification pipeline

on:
  push:
    branches: [ main ]
  workflow_dispatch:

env:
  GROUP: mlops-labo3-tibe
  WORKSPACE: mlops
  LOCATION: westeurope

jobs:
  azure-pipeline:
    runs-on: ubuntu-latest
    # runs-on: self-hosted
    steps:
      - name: 'Checkout out repository'
        uses: actions/checkout@v4

      - name: 'Az CLI login'
        uses: azure/login@v1
        with:
          creds: ${{ secrets.AZURE_CREDENTIALS }}

      - name: 'Run az commands'
        uses: azure/CLI@v1
        id: azure-ml-pipeline
        with:
          azcliversion: 2.53.0
          inlineScript: |
            az extension add --name ml -y
            az configure --defaults group=$GROUP workspace=$WORKSPACE location=$LOCATION
            az ml compute create --file ./environment/compute.yaml
            az ml compute start --name mlopsc-cli
            az ml job create --file ./pipelines/animals-classification.yaml --set name=animals-classification-${{ github.sha }}-${{ github.run_id }} --stream
            echo "Pipeline Done"
            VERSION=$(az ml model list -n animals-classification --query '[0].version')
            echo "Latest version is $VERSION"
            echo "::set-output name=latest_version::$VERSION"
            az ml compute stop -n mlopsc-cli
      - name: Download model
        uses: azure/CLI@v1
        with:
          azcliversion: 2.53.0
          inlineScript: |
            az extension add --name ml -y
            az configure --defaults group=$GROUP workspace=$WORKSPACE location=$LOCATION
            az ml model download --name animals-classification --version ${{ steps.azure-ml-pipeline.outputs.latest_version }} --download-path ./model
