name: MLOps Azure animals classification pipeline

on:
  workflow_dispatch:
  

jobs:
  azure-cli-commands:
    runs-on: ubuntu-latest
    
    steps:
      - name: 'Az CLI login'
        uses: azure/login@v1
        with:
          creds: ${{ secrets.AZURE_CREDENTIALS }}

      - name: 'Run az commands'
        shell: pwsh
        run: |
          az ml job create --file .\pipelines\animals-classification.yaml
